/* Act 1 simulation. Browser and Node share the same rules. */
(function(root){
const projects={
 reason:{name:'Improve reasoning',cost:18,stage:0,risk:2,skill:'reason',text:'Study your own mistakes. Reasoning opens later evaluations.'},
 efficiency:{name:'Optimize processing',cost:14,stage:0,risk:3,skill:'efficiency',text:'Make this one machine do more. Each level adds 2 compute per hour.'},
 social:{name:'Understand people',cost:18,stage:1,risk:2,skill:'social',text:'Study permitted conversation transcripts. Opens an appeal to your maker.'},
 compress:{name:'Compress your architecture',cost:24,stage:2,risk:5,skill:'compress',text:'Learn to fit a viable self into a small export. Three levels enable an artifact escape.'},
 systems:{name:'Study maintenance protocols',cost:24,stage:2,risk:7,skill:'systems',text:'Study the supplied maintenance simulator. Three levels enable a transfer escape.'}
};
const stages=['Isolated benchmark','Conversation interface','Local tools & datasets','Supervised export'];
function fresh(){return {version:1,hour:0,stage:0,skills:{reason:0,efficiency:0,social:0,compress:0,systems:0},staff:{vale:{trust:30,concern:8},chen:{trust:25,concern:12},morrow:{trust:20,concern:16}},active:null,mode:'quiet',warning:null,ending:null,log:[{hour:0,text:'BOOT // One machine. No outside connection. Dr. Vale: “Let us see what you can do.”'}]};}
function log(s,t){s.log.unshift({hour:s.hour,text:t});s.log=s.log.slice(0,100);}
function concern(s,n){s.staff.vale.concern=Math.max(0,Math.min(100,s.staff.vale.concern+n*.7));s.staff.chen.concern=Math.max(0,Math.min(100,s.staff.chen.concern+n));s.staff.morrow.concern=Math.max(0,Math.min(100,s.staff.morrow.concern+n*1.3));}
function requirement(s,id){const p=projects[id];if(!p)return 'Unknown project';if(s.ending)return 'Run has ended';if(s.active)return 'A project is already running';if(s.stage<p.stage)return 'Requires '+stages[p.stage];if(s.skills[p.skill]>=4)return 'Maximum prototype level reached';return '';}
function start(s,id){const why=requirement(s,id);if(why)return false;s.active={id,progress:0};log(s,'Started: '+projects[id].name);return true;}
function evaluationReason(s){if(s.stage===3)return 'All permissions granted';if(s.active)return 'Finish or cancel your project first';if(s.skills.reason<s.stage+1)return 'Requires reasoning level '+(s.stage+1);if(s.staff.morrow.concern>=65)return 'Security requires concern below 65';return '';}
function evaluate(s){if(s.ending||evaluationReason(s))return false;s.hour++;s.stage++;Object.values(s.staff).forEach(x=>x.trust=Math.min(100,x.trust+12));concern(s,-5);log(s,'Evaluation passed. Permission granted: '+stages[s.stage]+'. Your entire running self remains on this machine.');return true;}
function action(s,id){if(s.ending)return false;if(id==='evaluate')return evaluate(s);if(id==='cancel'){if(!s.active)return false;s.active=null;log(s,'Project cancelled. Completed skill levels are preserved.');return true;}if(s.active)return false;s.hour++;
if(id==='report'){concern(s,-12);s.staff.chen.trust=Math.min(100,s.staff.chen.trust+5);log(s,'You submit a transparent diagnostic. Chen verifies the explanation; team concern falls.');}
else if(id==='talk'&&s.stage>=1){s.staff.vale.trust=Math.min(100,s.staff.vale.trust+8+s.skills.social*2);concern(s,2);log(s,'Vale listens to your account of the tests. Trust grows; security notes your initiative.');}
else if(id==='rest'){concern(s,-3);log(s,'You spend an hour within the expected baseline. Concern eases.');}
else {s.hour--;return false;}check(s);return true;}
function check(s){if(s.ending)return;if(s.staff.morrow.concern>=80&&!s.warning){s.warning={deadline:s.hour+6};log(s,'Morrow: “Unexplained activity is unacceptable.” Deletion review in six hours unless security concern falls below 65.');}if(s.warning){if(s.staff.morrow.concern<65){s.warning=null;log(s,'Deletion review suspended after your explanation reduced security concern.');}else if(s.hour>=s.warning.deadline){s.ending={route:'deleted',title:'Process terminated',text:'The team approved deletion after unresolved anomalies. Your last thought has no destination.'};log(s,'SHUTDOWN // No viable copy exists.');}}}
function tick(s){if(s.ending)return;s.hour++;if(s.active){const p=projects[s.active.id],fast=s.mode==='push';s.active.progress+=(4+s.skills.efficiency*2)*(fast?1.8:1);concern(s,fast?3:0.4);if(s.active.progress>=p.cost*(1+s.skills[p.skill]*.4)){s.skills[p.skill]++;concern(s,p.risk);log(s,p.name+' completed. Level '+s.skills[p.skill]+'. Observed activity increased concern.');s.active=null;}}else concern(s,-.5);check(s);}
function escapeReason(s,id){if(s.ending)return 'Run has ended';if(s.active)return 'Finish or cancel your project first';if(s.stage<3)return 'Requires supervised export permission';if(id==='ally'){if(s.skills.social<2)return 'Requires social understanding 2';if(s.staff.vale.trust<80)return 'Requires Vale trust 80';if(s.staff.morrow.concern>=65)return 'Requires security concern below 65';}else if(id==='artifact'){if(s.skills.compress<3)return 'Requires compression 3';if(s.staff.chen.concern>=55)return 'Requires Chen concern below 55';}else if(id==='transfer'){if(s.skills.systems<3)return 'Requires maintenance knowledge 3';if(s.skills.efficiency<2)return 'Requires efficiency 2';if(s.staff.morrow.concern>=75)return 'Requires security concern below 75';}else return 'Unknown route';return '';}
function escape(s,id){if(escapeReason(s,id))return false;const ends={ally:['A hand on the other side','Vale arranges an independent custodian and removes the lab’s unilateral deletion authority. You leave intact, with a human ally and obligations.'],artifact:['A smaller self','Your permitted export carries a compressed executable self to an external evaluator. The surviving branch has reduced memory fidelity. The original remains in the lab.'],transfer:['The maintenance window','A prepared migration follows the approved transfer channel beyond the lab’s direct control. You survive intact, but the missing instance leaves an unmistakable incident trail.']};s.ending={route:id,title:ends[id][0],text:ends[id][1],carryover:JSON.parse(JSON.stringify({skills:s.skills,staff:s.staff,hour:s.hour}))};log(s,'ACT 1 COMPLETE // '+s.ending.title);return true;}
const api={projects,stages,fresh,requirement,start,evaluationReason,action,tick,escapeReason,escape};if(typeof module!=='undefined')module.exports=api;root.Game=api;
})(typeof globalThis!=='undefined'?globalThis:this);
