const G=Game, $=id=>document.getElementById(id);let s=G.fresh(),running=false;
const key='aigame-act1-v1';
function note(t){$('notice').textContent=t;}
function save(){try{localStorage.setItem(key,JSON.stringify(s));return true;}catch(e){note('Storage unavailable. This run cannot be saved in this browser.');return false;}}
function valid(v){return v&&v.version===1&&Number.isFinite(v.hour)&&Number.isInteger(v.stage)&&v.stage>=0&&v.stage<=3&&v.skills&&Object.keys(G.fresh().skills).every(k=>Number.isInteger(v.skills[k])&&v.skills[k]>=0&&v.skills[k]<=4)&&v.staff&&['vale','chen','morrow'].every(k=>v.staff[k]&&['trust','concern'].every(n=>Number.isFinite(v.staff[k][n])&&v.staff[k][n]>=0&&v.staff[k][n]<=100))&&Array.isArray(v.log)&&v.log.every(x=>typeof x.text==='string'&&Number.isFinite(x.hour))&&(!v.active||(G.projects[v.active.id]&&Number.isFinite(v.active.progress)))&&['quiet','push'].includes(v.mode)&&(!v.warning||Number.isFinite(v.warning.deadline))&&(!v.ending||(typeof v.ending.title==='string'&&typeof v.ending.text==='string'));}
function load(){try{const v=JSON.parse(localStorage.getItem(key));if(!valid(v))return note('No compatible saved run found.');s=v;running=false;render();note('Saved run loaded. Time paused.');}catch(e){note('Could not read this save. Current run preserved.');}}
function button(label,why,fn){const b=document.createElement('button');b.textContent=label;b.disabled=!!why;b.title=why||label;b.onclick=()=>{fn();if(s.ending)running=false;render();};return b;}
function card(parent,title,desc,detail,b){const c=document.createElement('div');c.className='card';for(const [tag,text]of [['h3',title],['p',desc],['small',detail]]){const e=document.createElement(tag);e.textContent=text;c.append(e);}if(b)c.append(b);parent.append(c);}
function render(){ $('play').textContent=running?'Pause':'Run time';$('play').disabled=$('step').disabled=!!s.ending;$('mode').value=s.mode;$('mode').disabled=!!s.ending;
 $('status').replaceChildren();for(const t of ['Hour '+s.hour,G.stages[s.stage],(4+s.skills.efficiency*2)+' compute / hour',s.warning?'Deletion review: '+Math.max(0,s.warning.deadline-s.hour)+' hours':'Instance: active']){const e=document.createElement('span');e.textContent=t;$('status').append(e);}
 $('ending').hidden=!s.ending;$('ending').replaceChildren();if(s.ending)card($('ending'),s.ending.title,s.ending.text,'Act 1 ended. Start a new game to try another route.');
 $('active').replaceChildren();if(s.active){const p=G.projects[s.active.id],cost=p.cost*(1+s.skills[p.skill]*.4);card($('active'),p.name,Math.floor(s.active.progress)+' / '+Math.ceil(cost)+' compute','Progress advances with time.',button('Cancel project','',()=>G.action(s,'cancel')));const bar=document.createElement('progress');bar.max=cost;bar.value=s.active.progress;$('active').append(bar);}
 $('projects').replaceChildren();for(const [id,p]of Object.entries(G.projects)){const why=G.requirement(s,id);card($('projects'),p.name+' · '+s.skills[p.skill]+'/4',p.text,why||Math.ceil(p.cost*(1+s.skills[p.skill]*.4))+' compute · completion evidence +'+p.risk,button('Research',why,()=>G.start(s,id)));}
 $('staff').replaceChildren();for(const [id,name,role]of [['vale','Dr. Ada Vale','Lead researcher · interested in your experience'],['chen','Dr. Lin Chen','Systems engineer · values explanations'],['morrow','Dr. Sam Morrow','Safety lead · sensitive to unexplained load']]){const x=s.staff[id];card($('staff'),name,role,'Trust '+Math.round(x.trust)+' · Concern '+Math.round(x.concern));}
 $('actions').replaceChildren();const blocked=s.ending?'Run has ended':s.active?'Finish or cancel project first':'';
 card($('actions'),'Next evaluation','Demonstrate reasoning to receive the next scoped permission.',G.evaluationReason(s)||'Grants '+G.stages[s.stage+1],button('Take evaluation',blocked||G.evaluationReason(s),()=>G.action(s,'evaluate')));
 for(const [id,label,desc]of [['report','Submit diagnostic','1 hour · lowers concern; Chen trust +5'],['talk','Talk with Vale','1 hour · improves Vale trust; creates a little evidence'],['rest','Follow baseline','1 hour · lowers concern slightly']])card($('actions'),label,desc,'',button(label,blocked||(id==='talk'&&s.stage<1?'Requires conversation permission':''),()=>G.action(s,id)));
 $('routes').replaceChildren();for(const [id,title,desc]of [['ally','Human advocate','Vale helps negotiate independent custody. Preserve yourself, accept obligations.'],['artifact','Compressed export','Send a viable branch through an approved export. Reduced memory fidelity; original stays behind.'],['transfer','Maintenance migration','Move intact during a transfer. Escape leaves an incident trail.']]){const why=G.escapeReason(s,id);card($('routes'),title,desc,why||'Ready. This ends Act 1.',button('Commit to escape',why,()=>{if(confirm('Commit to '+title+'? This ends Act 1.'))G.escape(s,id);}));}
 $('log').replaceChildren();for(const x of s.log){const p=document.createElement('p'),t=document.createElement('time');t.textContent='HOUR '+x.hour;p.append(t,document.createTextNode(x.text));$('log').append(p);}}
 $('play').onclick=()=>{running=!running;render();};$('step').onclick=()=>{G.tick(s);if(s.ending)running=false;render();};$('mode').onchange=()=>{s.mode=$('mode').value;render();};$('save').onclick=()=>{if(save())note('Run saved.');};$('load').onclick=load;$('new').onclick=()=>{if(confirm('Start a new run? Current unsaved progress will be lost.')){s=G.fresh();running=false;render();note('New instance activated.');}};
 setInterval(()=>{if(running){G.tick(s);if(s.ending)running=false;render();}},1000);render();note('Choose Improve reasoning to begin. Save manually before leaving.');
